# Generated by Django 4.2.1 on 2023-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('data', models.DateTimeField(verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запись',
            },
        ),
        migrations.CreateModel(
            name='ready',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=35, verbose_name='Марка машины')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография авто')),
            ],
        ),
    ]
