# Generated by Django 4.2.1 on 2023-05-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ready',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=35, verbose_name='Марка машины')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография авто')),
            ],
        ),
    ]
