# Generated by Django 4.2.1 on 2023-05-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ready',
            options={'verbose_name': 'Наши работы'},
        ),
    ]
